service: vote-brexit

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2

functions:
  app:
    handler: src/server/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
